---
domain: vagrant-wp.local
doc_root: /var/www/wordpress

db:
  name: wordpress
  user: wp_user
  password: wp_pswd

ssl_dir: "{{nginx.dir}}/ssl/{{domain}}"
ssl_cert: 'self-signed'
cert:
  Country: JP
  State: Tokyo
  Locality: Minato-ku
  OrganizationalName: Default Company Ltd
  OrganizationalUnit: ""
  CommonName: "{{domain}}"
  Email: ""
  challenge_password: ''
  optional_company: ''
