- name: switch certbot-auto to webroot
  command: /usr/local/certbot/certbot-auto certonly --webroot -w {{doc_root}} -d {{domain}} -m {{letsencrypt_mail}} --agree-tos -n --force-renewal

- name: add renew cert to crontab
  cron:
    name: letsencrypt renew
    day: 1
    hour: 4
    job: "/usr/local/certbot/certbot-auto renew && /bin/systemctl reload nginx"
  tags:
    - letsencrypt
