---
- name: add remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: install php
  yum: name={{item}} state=present enablerepo=remi,remi-php70
  with_items:
    - php
    - php-mysqlnd
    - php-gd
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-mcrypt
    - php-fpm
    - php-opcache
    - php-apcu
  tags:
    - php

- name: enable php-fpm
  service: name=php-fpm state=started enabled=yes
  tags:
    - php

- name: change php-fpm config
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf backup=yes
  notify: restart php-fpm
  tags:
    - php

# SSL
- name: make ssl dir
  file: path={{ssl.dir}} state=directory

- name: generate private key, csr and crt
  shell: |
    openssl req -x509 -nodes -new -newkey rsa:2048 -keyout server.key -out server.crt \
    -subj "/C={{ssl.Country}}/ST={{ssl.State}}/L={{ssl.Locality}}/CN={{ssl.CommonName}}" chdir="{{ssl.dir}}"
  args:
    creates: "{{ssl.dir}}/server.crt"

- name: change nginx defaut.conf for php
  template: src=nginx_default.conf.j2 dest=/etc/nginx/conf.d/default.conf backup=yes
  notify: restart nginx
  tags:
    - php
    - nginx
