---
- name: add remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: install php
  yum: name={{item}} state=present enablerepo=remi,remi-php70
  with_items:
    - php
    - php-mysqlnd
    - php-gd
    - php-xml
    - php-xmlrpc
    - php-mbstring
    - php-mcrypt
    - php-fpm
    - php-opcache
    - php-apcu
  tags:
    - php

- name: enable php-fpm
  service: name=php-fpm state=started enabled=yes
  tags:
    - php

- name: change php-fpm config
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf backup=yes
  notify: restart php-fpm
  tags:
    - php
