- name: install avahi
  yum: name={{item}} state=present
  with_items:
    - avahi
    - avahi-tools
    - avahi-ui-tools # for python-avahi

- name: enable avahi
  service: name=avahi-daemon state=started enabled=yes

# https://github.com/airtonix/avahi-aliases
- pip: name='git+http://github.com/airtonix/avahi-aliases.git' editable=false

- copy: src=avahi-aliases.service dest=/etc/systemd/system/avahi-aliases.service

- name: enable avahi-aliases
  service: name=avahi-aliases state=started enabled=yes

# firewall setting
- shell: firewall-cmd --list-all|grep 5353/udp
  register: fw
  changed_when: fw.rc !=0
  ignore_errors: yes

- name: open avahi port
  firewalld: port=5353/udp permanent=true state=enabled
  notify: reload firewalld
  when: fw.rc != 0
