---
# なぜか動かないのでコメントアウト。代わりにファイルをコピーする
# - name: add nginx repository
#   yum_repository:
#     name: nginx
#     description: nginx repository
#     baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
#     gpgcheck: 0
#     enabled: 0

- name: add nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name=nginx state=present enablerepo=nginx
  tags:
    - nginx

- name: enable nginx
  service: name=nginx state=started enabled=yes
  tags:
    - nginx

- name: make nginx.service.d directory
  file: path=/etc/systemd/system/nginx.service.d/ state=directory

- name: set nofile limit config
  template:
    src: nofile_limit.conf.j2
    dest: /etc/systemd/system/nginx.service.d/nofile_limit.conf
  notify: reload systemd

# modify nginx.conf
- name: set nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes
  notify: restart nginx
  tags:
    - nginx
