---
# なぜか動かないのでコメントアウト。代わりにファイルをコピーする
# - name: add nginx repository
#   yum_repository:
#     name: nginx
#     description: nginx repository
#     baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
#     gpgcheck: 0
#     enabled: 0

- name: add nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name={{item}} state=present enablerepo=nginx
  with_items:
    - nginx
    - MySQL-python
  tags:
    - nginx

- name: enable nginx
  service: name=nginx state=started enabled=yes
  tags:
    - nginx

- name: make nginx.service.d directory
  file: path=/etc/systemd/system/nginx.service.d/ state=directory

- name: set nofile limit config
  template:
    src: nofile_limit.conf.j2
    dest: /etc/systemd/system/nginx.service.d/nofile_limit.conf
  notify: reload systemd

# modify nginx.conf
- name: set nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes
  notify: restart nginx
  tags:
    - nginx

# SSL
- name: make nginx ssl dir
  file: path="{{nginx.dir}}/ssl" state=directory

- name: generate private key, csr and crt
  shell: |
    openssl req -x509 -nodes -new -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem \
    -subj "/C={{default_cert.Country}}/ST={{default_cert.State}}/L={{default_cert.Locality}}/CN={{default_cert.CommonName}}" chdir="{{default_ssl_dir}}"
  args:
    creates: "{{nginx.dir}}/ssl/privkey.pem"

- name: generate dhparam.pem
  command: openssl dhparam 2048 -out {{nginx.dir}}/ssl/dhparam.pem
  args:
    creates: "{{nginx.dir}}/ssl/dhparam.pem"
