---
- name: install firewalld
  yum: name=firewalld state=present

- name: enable firewalld
  service: name=firewalld state=started enabled=yes
  tags:
    - firewalld

- name: add interfeces
  firewalld: interface={{item}} zone=public permanent=true state=enabled
  with_items: "{{open_interfaces}}"
  notify: reload firewalld

- name: open services
  firewalld: service={{item}} permanent=true state=enabled
  with_items:
    - http
    - https
  notify: reload firewalld

- name: open ports
  firewalld:
    port: "{{item}}"
    permanent: true
    state: enabled
  with_items: "{{open_ports}}"
  notify: reload firewalld

