---
- shell: localectl status |grep {{base.locale}}
  register: locale
  changed_when: locale.rc != 0
  ignore_errors: yes

- name: set locale
  command: localectl set-locale {{base.locale}}
  when: locale.rc != 0

- shell: timedatectl status|grep {{base.timezone}}
  register: timezone
  changed_when: timezone.rc != 0
  ignore_errors: yes

- name: set timezone
  command: timedatectl set-timezone {{base.timezone}}
  when: timezone.rc != 0

- name: add epel repository
  yum: name=epel-release state=present

- name: yum upgrade
  yum: name=* state=latest

- name: install basic packages
  yum: name={{item}} state=present
  with_items:
    - vim
    - ntp
    - bash-completion
    - zip
    - unzip
    - git
    - selinux-policy-targeted
    - selinux-policy-devel
    - python-pip

- name: enable ntp
  service: name=ntpd state=started enabled=yes

- name: set fs.file-max
  sysctl: name=fs.file-max value={{sysctl.fs.file_max}} state=present

# bash setting
- name: put /etc/util.sh
  copy: src=util.sh dest=/etc/profile.d/util.sh

- name: put inputrc-ext
  copy: src=inputrc-ext dest=/etc/inputrc-ext

- shell: grep '/etc/inputrc-ext' /etc/inputrc
  register: result
  changed_when: result.rc != 0
  ignore_errors: yes

- name: modify inputrc
  shell: echo '$include /etc/inputrc-ext' >> /etc/inputrc
  when: result.rc != 0
