---
- shell: localectl status |grep {{base.locale}}
  register: locale
  changed_when: locale.rc != 0
  ignore_errors: yes

- name: set locale
  command: localectl set-locale {{base.locale}}
  when: locale.rc != 0

- name: set timezone
  timezone:
    name: "{{ base.timezone }}"

- name: add epel repository
  yum: name=epel-release state=present

- name: yum upgrade
  yum: name=* state=latest

- name: install basic packages
  yum: name={{item}} state=present
  with_items:
    - vim
    - ntp
    - bash-completion
    - zip
    - unzip
    - git
    - selinux-policy-targeted
    - selinux-policy-devel
    - python-pip

- name: enable ntp
  service: name=ntpd state=started enabled=yes

- name: set fs.file-max
  sysctl: name=fs.file-max value={{sysctl.fs.file_max}} state=present

# bash setting
- name: put /etc/util.sh
  copy: src=util.sh dest=/etc/profile.d/util.sh

- name: put inputrc-ext
  copy: src=inputrc-ext dest=/etc/inputrc-ext

- name: include inputrc-ext
  lineinfile: dest=/etc/inputrc line='$include /etc/inputrc-ext'
