---
- hosts: all
  become: yes
  vars_files:
    - vars/{{stage}}.yml
  roles:
    - base
    - mariadb
    - nginx
    - php
    - security
    - letsencrypt
    - wordpress

- hosts: vagrant
  become: yes
  vars_files:
      - vars/{{stage}}.yml
  roles:
    - avahi
