---
- name: prepare database
  include: database.yml

- name: download wordpress
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /usr/local/src/wordpress.tar.gz

- name: install wordpress
  unarchive:
    src: /usr/local/src/wordpress.tar.gz
    dest: /var/www
    group: "{{php_fpm.group}}"
    owner: "{{php_fpm.user}}"
    copy: no
    creates: /var/www/wordpress

- name: create self siged cert
  include: self_signed_cert.yml
  when: ssl_cert=="self-signed"

- name: change nginx defaut.conf for php
  template: src=nginx_wordpress.conf.j2 dest=/etc/nginx/conf.d/wordpress.conf backup=yes
  notify:
    - restart php-fpm
    - restart nginx
  tags:
    - php
    - nginx
