---
- name: prepare database
  include: database.yml

- name: deploy wordpress
  include: wordpress.yml
  when: wordpress=="wordpress"

- name: restore own wordpress
  include: restore_own_wp.yml
  when: wordpress=="own_wp"

- name: create self siged cert
  include: self_signed_cert.yml
  when: ssl_cert=="self-signed"

- name: create letsencrypt cert
  include: letsencrypt_cert.yml
  when: ssl_cert=="letsencrypt"
  tags:
    - letsencrypt

- name: change nginx {{domain}}.conf
  template: src=nginx_wordpress.conf.j2 dest=/etc/nginx/conf.d/{{domain}}.conf backup=yes
  notify:
    - restart php-fpm
    - restart nginx
  tags:
    - php
    - nginx
