---
- name: add wordpress db
  mysql_db:
    name: "{{db.name}}"
    encoding: utf8
    state: present

- name: add worpdress db user
  mysql_user:
    name: "{{db.user}}"
    password: "{{db.password}}"
    priv: "{{db.name}}.*:ALL"
    host: localhost

- name: download wordpress
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /usr/local/src/wordpress.tar.gz

- name: install wordpress
  unarchive:
    src: /usr/local/src/wordpress.tar.gz
    dest: /var/www
    group: "{{php_fpm.group}}"
    owner: "{{php_fpm.user}}"
    copy: no
    creates: /var/www/wordpress

- name: generate wordpress cert directory
  file: path="{{ssl_dir}}" state=directory

- debug: msg="wordpress {{ssl_dir}}"

- name: generate wordpress private key, csr and crt
  shell: |
    openssl req -x509 -nodes -new -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem \
    -subj "/C={{cert.Country}}/ST={{cert.State}}/L={{cert.Locality}}/CN={{cert.CommonName}}" chdir="{{ssl_dir}}"
  args:
    creates: "{{ssl_dir}}/fullchain.pem"

- name: change nginx defaut.conf for php
  template: src=nginx_wordpress.conf.j2 dest=/etc/nginx/conf.d/wordpress.conf backup=yes
  notify:
    - restart php-fpm
    - restart nginx
  tags:
    - php
    - nginx
