---
- name: download wordpress
  get_url:
    url: https://ja.wordpress.org/latest-ja.tar.gz
    dest: /usr/local/src/wordpress.tar.gz

- name: install wordpress
  unarchive:
    src: /usr/local/src/wordpress.tar.gz
    dest: /usr/local/src
    group: "{{php_fpm.group}}"
    owner: "{{php_fpm.user}}"
    copy: no
    creates: "{{doc_root}}"

- name: move to doc root
  shell: mv /usr/local/src/wordpress {{doc_root}}
  args:
    creates: "{{doc_root}}"

- name: chown doc root
  shell: chown -R {{php_fpm.user}}.{{php_fpm.group}} {{doc_root}}
