---
- name: add mariadb.repo
  template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo

- name: install mariadb
  yum: name={{item}} state=present enablerepo=mariadb
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python
  tags:
    - mariadb

- name: enable mariadb
  service: name=mariadb state=started enabled=yes
  tags:
    - mariadb

- name: set mysql root password
  include: root_password.yml
  when: db_root_password is defined
