---
- name: set root password
  mysql_user: name=root host={{item}} password={{db_root_password}}
  with_items:
      - ::1
      - 127.0.0.1
      - localhost

- name: create root .my.cnf
  template: src=my.cnf.j2  dest=/root/.my.cnf mode=0600